/* Generates the markdown corpus in /content/articles.
   Run once:  node scripts/seed-content.js
   After this, articles are ordinary .md files edited via /admin or by hand. */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'content/articles');
mkdirSync(outDir, { recursive: true });

const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[''']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

/* ---- the newsroom ---- */
const A = {
  adaeze: ['Adaeze Okonkwo', 'West Africa correspondent', 'Lagos'],
  rafael: ['Rafael Duarte Lima', 'Latin America correspondent', 'São Paulo'],
  mei: ['Mei-Lin Chow', 'China tech correspondent', 'Taipei'],
  priya: ['Priya Raghunathan', 'South Asia correspondent', 'Bengaluru'],
  yusuf: ['Yusuf El-Amin', 'Gulf and North Africa correspondent', 'Cairo'],
  ines: ['Inés Villalba', 'Andes correspondent', 'Bogotá'],
  tomas: ['Tomás Brekalo', 'Eastern Europe correspondent', 'Zagreb'],
  nadia: ['Nadia Farouk', 'Investigations editor', 'Beirut'],
  kwame: ['Kwame Boateng', 'Infrastructure reporter', 'Accra'],
  hana: ['Hana Yoshida', 'Labour and automation reporter', 'Osaka'],
  soraya: ['Soraya Mbeki', 'Southern Africa correspondent', 'Johannesburg'],
  dmitri: ['Dmitri Anselm', 'Compute and chips reporter', 'Vilnius'],
  lucia: ['Lúcia Ferrão', 'Culture correspondent', 'Lisbon'],
  arun: ['Arun Sethi', 'Open source reporter', 'Delhi'],
  staff: ['Ground Truth staff', 'Newsroom', 'Global']
};

const S = {
  race: 'The AI Race',
  life: 'AI & Everyday Life',
  work: 'Work After Automation',
  power: 'Machines and Power',
  south: 'AI in the Global South',
  data: 'The Human Dataset',
  climate: 'Climate, Chips & Infrastructure',
  culture: 'Culture, Media & Synthetic Reality',
  open: 'Open Source and the Commons'
};

/* title, dek, section, authorKey, kind, tags, date, readTime, weight, flags */
const stories = [
  // ───────── hero + just-in ─────────
  [
    'The AI boom is reaching places investors forgot to look',
    'Data centre money is landing in towns that were promised fibre optics a decade ago and never got them. Six months of records requests across four countries show who is actually being paid — and who is paying.',
    S.race, 'nadia', 'Investigation', ['data centres', 'investment', 'infrastructure'],
    '2026-09-17', 18, 1, { featured: true }
  ],
  [
    'The next AI race may be about electricity, not models',
    'Every frontier lab now employs people whose only job is finding power. The grid operators they call are not ready for the conversation.',
    S.climate, 'kwame', 'Analysis', ['energy', 'grid', 'compute'],
    '2026-09-17', 9, 1, { secondary: true }
  ],
  [
    'What happens when a chatbot becomes your co-worker?',
    'At a Manila outsourcing firm, an assistant was introduced to help. Eighteen months on, staff describe negotiating with it for their own shifts.',
    S.work, 'hana', 'Report', ['labour', 'outsourcing'],
    '2026-09-16', 11, 1, {}
  ],
  [
    'The hidden workers teaching machines how to see',
    'Annotation work moved from Nairobi to smaller cities where wages are lower and contracts shorter. The labellers describe a job that keeps getting faster.',
    S.data, 'adaeze', 'Investigation', ['labelling', 'labour', 'supply chain'],
    '2026-09-16', 14, 1, {}
  ],
  [
    'Small languages are building their own AI futures',
    'Speakers of languages the big models handle badly have stopped waiting to be included. What they are building instead looks nothing like a frontier lab.',
    S.open, 'arun', 'Feature', ['language', 'open source', 'community'],
    '2026-09-15', 13, 1, {}
  ],
  [
    'Who owns the data generated by ordinary life?',
    'A ruling in Brasília gave people a claim over data collected from public space. Three other countries are now drafting from the same text.',
    S.power, 'rafael', 'Report', ['privacy', 'regulation', 'courts'],
    '2026-09-15', 10, 1, {}
  ],

  // ───────── The AI Race ─────────
  [
    'Two labs, one grid, and a city that was not consulted',
    'The council learned about the second data centre from a planning notice taped to a fence.',
    S.race, 'ines', 'Report', ['data centres', 'planning'], '2026-09-14', 8, 2, {}
  ],
  [
    'Chinese open-weight models are winning on price, not benchmarks',
    'Developers across Southeast Asia are switching for reasons that have little to do with capability.',
    S.race, 'mei', 'Analysis', ['open weights', 'china', 'pricing'], '2026-09-13', 7, 3, {}
  ],
  [
    'The quiet consolidation of the AI supply chain',
    'Four companies now sit between a model and the electricity it runs on.',
    S.race, 'dmitri', 'Explainer', ['supply chain', 'chips'], '2026-09-12', 6, 4, {}
  ],

  // ───────── AI & Everyday Life ─────────
  [
    'The pharmacist in Quetta who became a triage system',
    'When the nearest doctor is four hours away, a phone model starts making decisions nobody designed it to make.',
    S.life, 'priya', 'Dispatch', ['health', 'access'], '2026-09-14', 9, 1, {}
  ],
  [
    'Marriage brokers, matchmakers, and the model in between',
    'Families in three Indian cities describe outsourcing the first conversation.',
    S.life, 'priya', 'Feature', ['culture', 'relationships'], '2026-09-12', 11, 2, {}
  ],
  [
    'Your landlord may already be using AI to price your rent',
    'The software is sold as market analysis. Tenants describe something closer to coordination.',
    S.life, 'rafael', 'Investigation', ['housing', 'pricing'], '2026-09-11', 12, 3, {}
  ],
  [
    'The school that banned AI, then quietly unbanned it',
    'Teachers in Kraków spent a year arguing. The compromise they reached is stranger than either position.',
    S.life, 'tomas', 'Report', ['education'], '2026-09-10', 8, 4, {}
  ],

  // ───────── Work After Automation ─────────
  [
    'Translators did not disappear. Their rates did.',
    'The work is still there. What changed is who sets the price and how fast it must be delivered.',
    S.work, 'lucia', 'Report', ['labour', 'translation'], '2026-09-13', 10, 2, {}
  ],
  [
    'A union contract that treats a model as a piece of equipment',
    'Port workers in Valparaíso negotiated language that other unions are already copying.',
    S.work, 'ines', 'Report', ['unions', 'labour'], '2026-09-11', 9, 3, {}
  ],
  [
    'The rise of the prompt supervisor',
    'A job that did not exist three years ago now has a pay band, a career ladder, and a burnout problem.',
    S.work, 'hana', 'Feature', ['jobs', 'labour'], '2026-09-09', 8, 4, {}
  ],

  // ───────── Machines and Power ─────────
  [
    'The procurement documents that show how a country buys surveillance',
    'Contracts obtained from four ministries reveal a standard template circulating between governments.',
    S.power, 'nadia', 'Investigation', ['surveillance', 'procurement'], '2026-09-14', 16, 2, {}
  ],
  [
    'Election officials are being sold AI they did not ask for',
    'Vendors are bundling detection tools into contracts for ordinary voter roll software.',
    S.power, 'soraya', 'Report', ['elections', 'procurement'], '2026-09-12', 9, 3, {}
  ],
  [
    'When the regulator and the regulated share the same consultants',
    'A review of disclosure filings in three jurisdictions found the same six firms on both sides.',
    S.power, 'tomas', 'Investigation', ['regulation', 'lobbying'], '2026-09-10', 13, 4, {}
  ],

  // ───────── AI in the Global South ─────────
  [
    'Lagos built an AI cluster. Then the power went out.',
    'The generators cost more than the GPUs. Nobody budgeted for that.',
    S.south, 'adaeze', 'Feature', ['infrastructure', 'energy'], '2026-09-13', 12, 1, {}
  ],
  [
    'The Nairobi annotators who unionised, and what happened next',
    'Two years after the first contract, the work has moved and the union is following it.',
    S.south, 'soraya', 'Report', ['labour', 'unions'], '2026-09-11', 11, 2, {}
  ],
  [
    'Indonesia is writing AI rules for a market it does not control',
    'Regulators describe drafting law for systems they cannot inspect.',
    S.south, 'mei', 'Analysis', ['regulation', 'policy'], '2026-09-09', 8, 3, {}
  ],
  [
    'A model trained on Amazonian field notes, by the people who wrote them',
    'Researchers in Manaus kept the data and licensed the outputs. It took four years.',
    S.south, 'rafael', 'Feature', ['research', 'data sovereignty'], '2026-09-08', 14, 4, {}
  ],

  // ───────── The Human Dataset ─────────
  [
    'Every photo you posted in 2011 is still working',
    'Researchers traced a single archive through eleven downstream training sets.',
    S.data, 'nadia', 'Investigation', ['training data', 'privacy'], '2026-09-12', 15, 2, {}
  ],
  [
    'The consent form nobody could read',
    'A clinic in Amman collected scans for research. The terms were four screens of English.',
    S.data, 'yusuf', 'Report', ['health', 'consent'], '2026-09-10', 9, 3, {}
  ],
  [
    'What a data broker actually sells, line by line',
    'We bought a sample. Here is what was in it.',
    S.data, 'staff', 'Explainer', ['data brokers', 'privacy'], '2026-09-07', 7, 4, {}
  ],

  // ───────── Climate, Chips & Infrastructure ─────────
  [
    'The water bill a data centre does not have to publish',
    'In five of seven jurisdictions we checked, consumption figures are exempt from disclosure.',
    S.climate, 'kwame', 'Investigation', ['water', 'data centres'], '2026-09-12', 13, 2, {}
  ],
  [
    'Chip fabs are chasing cold air and cheap power to strange places',
    'Northern Sweden, northern Japan, and a valley in Chile are competing for the same three customers.',
    S.climate, 'dmitri', 'Report', ['chips', 'energy'], '2026-09-10', 10, 3, {}
  ],
  [
    'The grid operator who says no',
    'A utility in Ireland began refusing connection requests. Others are watching what happens.',
    S.climate, 'tomas', 'Q&A', ['grid', 'energy'], '2026-09-08', 8, 4, {}
  ],

  // ───────── Culture, Media & Synthetic Reality ─────────
  [
    'The film industry that decided to label everything',
    "Nigeria's producers agreed on disclosure rules before any regulator asked.",
    S.culture, 'adaeze', 'Report', ['film', 'disclosure'], '2026-09-13', 9, 1, {}
  ],
  [
    'A voice actor is suing over a performance she never gave',
    'The case turns on whether a voice is a work or a person.',
    S.culture, 'lucia', 'Report', ['copyright', 'voice'], '2026-09-11', 10, 2, {}
  ],
  [
    'Synthetic anchors are reading the news in twelve countries',
    'Most audiences can tell. Broadcasters are running them anyway, and explaining why.',
    S.culture, 'yusuf', 'Feature', ['broadcast', 'synthetic media'], '2026-09-09', 11, 3, {}
  ],
  [
    'The archive that refuses to be scraped',
    'A Lisbon photo collection built a licence that machines cannot quietly ignore.',
    S.culture, 'lucia', 'Dispatch', ['archives', 'licensing'], '2026-09-07', 7, 4, {}
  ],

  // ───────── Open Source and the Commons ─────────
  [
    'The maintainer burnout behind half the AI stack',
    'Four people maintain libraries that almost every model depends on. Three want out.',
    S.open, 'arun', 'Investigation', ['open source', 'maintainers'], '2026-09-12', 14, 2, {}
  ],
  [
    'What "open" means when the weights are free and the data is not',
    'A field guide to the licences now competing for the word.',
    S.open, 'staff', 'Explainer', ['licensing', 'open weights'], '2026-09-10', 8, 3, {}
  ],
  [
    'A public compute cluster, run like a library',
    'Researchers in Ljubljana built shared infrastructure with a lending model. It is fully booked.',
    S.open, 'tomas', 'Feature', ['compute', 'public infrastructure'], '2026-09-08', 12, 4, {}
  ],
  [
    'The commons is not a licence. It is a maintenance budget.',
    'Why the money keeps arriving for models and never for the plumbing.',
    S.open, 'arun', 'Analysis', ['funding', 'open source'], '2026-09-06', 9, 5, {}
  ]
];

const body = (title, dek, kind) => `
${dek}

## What we found

Reporting for this ${kind.toLowerCase()} began with a single question and a
records request that took four months to answer. The documents that came back
described a process nobody involved was willing to explain on the record — so we
went to the people it affected instead.

What follows is drawn from eighteen interviews, a review of contracts obtained
under freedom of information law, and two weeks of reporting on the ground. Where
we could not confirm a claim independently, we have said so.

## The pattern

The same arrangement appears in three other places we checked. Each time, the
terms were slightly different and the outcome was roughly the same: a decision
made quickly, at a scale nobody had planned for, in a jurisdiction where the
rules had not yet been written.

> "Nobody asked us. We found out the way everyone else found out."

That sentence, or a close version of it, came up in nearly every conversation.

## What happens next

Two of the authorities we contacted have opened reviews. A third declined to
comment. We will continue reporting this story, and we publish corrections in
the open — if you know something about it, the newsroom's contact details are at
the bottom of this page.
`.trim();

let count = 0;
for (const [title, dek, section, authorKey, kind, tags, date, readTime, weight, flags] of stories) {
  const [author, authorTitle, location] = A[authorKey];
  const slug = slugify(title);
  const fm = [
    '---',
    `title: ${JSON.stringify(title)}`,
    `dek: ${JSON.stringify(dek)}`,
    `section: ${JSON.stringify(section)}`,
    `kind: ${JSON.stringify(kind)}`,
    `author: ${JSON.stringify(author)}`,
    `authorTitle: ${JSON.stringify(authorTitle)}`,
    `location: ${JSON.stringify(location)}`,
    `tags: [${tags.map((t) => JSON.stringify(t)).join(', ')}]`,
    `date: ${date}`,
    `readTime: ${readTime}`,
    `weight: ${weight}`,
    `featured: ${!!flags.featured}`,
    `secondary: ${!!flags.secondary}`,
    '---',
    ''
  ].join('\n');

  writeFileSync(resolve(outDir, `${slug}.md`), fm + body(title, dek, kind) + '\n', 'utf8');
  count++;
}

console.log(`wrote ${count} articles to content/articles/`);
